
[package]
name = "solders-transaction-status"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders transaction status crate."

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
derive_more = { workspace = true }
pyo3 = { workspace = true, features = ["macros"] }
pythonize = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-account-decoder-client-types = { workspace = true }
solana-reward-info = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
solders-account-decoder = { workspace = true }
solders-hash = { workspace = true }
solders-macros = { workspace = true }
solders-message = { workspace = true }
solders-pubkey = { workspace = true }
solders-signature = { workspace = true }
solders-traits-core = { workspace = true }
solders-transaction = { workspace = true }
solders-transaction-confirmation-status = { workspace = true }
solders-transaction-error = { workspace = true }
solders-transaction-return-data = { workspace = true }
solders-transaction-status-enums = { workspace = true }
solders-transaction-status-struct = { workspace = true }
