
[package]
name = "solders-rpc-responses"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders RPC responses crate."

[dependencies]
camelpaste = { workspace = true }
derive_more = { workspace = true }
pyo3 = { workspace = true, features = ["macros"] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
solana-account-decoder-client-types = { workspace = true }
solana-rpc-client-api = { workspace = true }
solana-transaction-status-client-types = { workspace = true }
solders-account = { workspace = true }
solders-account-decoder = { workspace = true }
solders-epoch-info = { workspace = true }
solders-hash = { workspace = true }
solders-macros = { workspace = true }
solders-primitives = { workspace = true }
solders-pubkey = { workspace = true }
solders-rpc-common = { workspace = true }
solders-rpc-errors-no-tx-status = { workspace = true }
solders-rpc-errors-tx-status = { workspace = true }
solders-rpc-response-data-boilerplate = { workspace = true }
solders-rpc-responses-common = { workspace = true }
solders-rpc-responses-tx-status = { workspace = true }
solders-rpc-version = { workspace = true }
solders-signature = { workspace = true }
solders-traits = { workspace = true }
solders-traits-core = { workspace = true }
solders-transaction-error = { workspace = true }
solders-transaction-status = { workspace = true }
solders-transaction-status-struct = { workspace = true }
thiserror = { workspace = true }
