
[package]
name = "solders-rpc-sig-status-config"
version = { workspace = true }
edition = { workspace = true }
include = ["/src"]
license = { workspace = true }
repository = { workspace = true }
description = "Solders RPC signature status config crate."

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
serde = { workspace = true }
solders-macros = { workspace = true }
solana-rpc-client-api = { workspace = true }
solders-rpc-config-macros = { workspace = true }
solders-traits-core = { workspace = true }
